/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplo;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Notas extends javax.swing.JFrame {

    /**
     * Creates new form Notas
     */
    public Notas() {
        initComponents();
        modeloLista();
    }
    
    public void modeloLista(){
        DefaultListModel<String> modelo = new DefaultListModel<String>();
        modelo.addElement("Nota 1");
        jslLista.setModel(modelo);
    }
    
    public void limpiar(){
        jtxaTexto.setText("");
    }
    
    public void nuevaNota(){
        DefaultListModel<String> modelo = (DefaultListModel<String>) jslLista.getModel();
        modelo.addElement("Nueva Nota");
        jslLista.setSelectedIndex(modelo.getSize()-1);
    }

    public void eliminaNota(){
        DefaultListModel<String> modelo = (DefaultListModel<String>) jslLista.getModel();
        int index = jslLista.getSelectedIndex();
        if(index!=-1){
            modelo.remove(index);
        }
    }
    
    public void cambiarNombre(){
        int index = jslLista.getSelectedIndex();
        if(index!=-1){
            String nombre = JOptionPane.showInputDialog(this,"ingrese algo");
            if(nombre!=null && !nombre.trim().isEmpty()){
                DefaultListModel<String> modelo = (DefaultListModel<String>) jslLista.getModel();
                modelo.set(index, nombre);
            }
        }
    }
    
    public void cargarNota(){
        String seleccionado = (String) jslLista.getSelectedValue();
        if(seleccionado!= null){
            jtxaTexto.setText("Contenido de:"+seleccionado);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbtnAñadir = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jsplDivision = new javax.swing.JSplitPane();
        jpnlLista = new javax.swing.JPanel();
        jsrcLista = new javax.swing.JScrollPane();
        jslLista = new javax.swing.JList<>();
        jtbnEditorMensaje = new javax.swing.JTabbedPane();
        jpnlEditor = new javax.swing.JPanel();
        jscrEditor = new javax.swing.JScrollPane();
        jtxaTexto = new javax.swing.JTextArea();
        jpnlMensaje = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jbtnAñadir.setText("Añadir");
        jbtnAñadir.setFocusable(false);
        jbtnAñadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAñadir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAñadirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnAñadir);

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.setFocusable(false);
        jbtnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnLimpiar);

        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.setFocusable(false);
        jbtnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnEliminar);

        jbtnSalir.setText("Salir");
        jbtnSalir.setFocusable(false);
        jbtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnSalir);

        jsplDivision.setDividerLocation(200);

        jslLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jslListaMouseClicked(evt);
            }
        });
        jslLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jslListaValueChanged(evt);
            }
        });
        jsrcLista.setViewportView(jslLista);

        javax.swing.GroupLayout jpnlListaLayout = new javax.swing.GroupLayout(jpnlLista);
        jpnlLista.setLayout(jpnlListaLayout);
        jpnlListaLayout.setHorizontalGroup(
            jpnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsrcLista, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jpnlListaLayout.setVerticalGroup(
            jpnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsrcLista, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );

        jsplDivision.setLeftComponent(jpnlLista);

        jtxaTexto.setColumns(20);
        jtxaTexto.setRows(5);
        jscrEditor.setViewportView(jtxaTexto);

        javax.swing.GroupLayout jpnlEditorLayout = new javax.swing.GroupLayout(jpnlEditor);
        jpnlEditor.setLayout(jpnlEditorLayout);
        jpnlEditorLayout.setHorizontalGroup(
            jpnlEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlEditorLayout.createSequentialGroup()
                .addComponent(jscrEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnlEditorLayout.setVerticalGroup(
            jpnlEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscrEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );

        jtbnEditorMensaje.addTab("Editor de texto", jpnlEditor);

        jLabel1.setText("Este es un mensaje");

        javax.swing.GroupLayout jpnlMensajeLayout = new javax.swing.GroupLayout(jpnlMensaje);
        jpnlMensaje.setLayout(jpnlMensajeLayout);
        jpnlMensajeLayout.setHorizontalGroup(
            jpnlMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMensajeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );
        jpnlMensajeLayout.setVerticalGroup(
            jpnlMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMensajeLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 218, Short.MAX_VALUE))
        );

        jtbnEditorMensaje.addTab("Mensaje", jpnlMensaje);

        jsplDivision.setRightComponent(jtbnEditorMensaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jsplDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsplDivision))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAñadirActionPerformed
nuevaNota();
        
    }//GEN-LAST:event_jbtnAñadirActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
eliminaNota();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jslListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jslListaMouseClicked
        if(evt.getClickCount()==2){
        cambiarNombre();}
    }//GEN-LAST:event_jslListaMouseClicked

    private void jslListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jslListaValueChanged
        if(!evt.getValueIsAdjusting()){
        cargarNota();    
        }
    }//GEN-LAST:event_jslListaValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtnAñadir;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JPanel jpnlEditor;
    private javax.swing.JPanel jpnlLista;
    private javax.swing.JPanel jpnlMensaje;
    private javax.swing.JScrollPane jscrEditor;
    private javax.swing.JList<String> jslLista;
    private javax.swing.JSplitPane jsplDivision;
    private javax.swing.JScrollPane jsrcLista;
    private javax.swing.JTabbedPane jtbnEditorMensaje;
    private javax.swing.JTextArea jtxaTexto;
    // End of variables declaration//GEN-END:variables
}
