/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplo;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Personaje extends javax.swing.JFrame {

    /**
     * Creates new form Personaje
     */
    public Personaje() {
        initComponents();
        setLocationRelativeTo(null); // Centrar ventana
        setResizable(false);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/ejemplo/icon.png")).getImage()); // Icono personalizado (agrega icon.png en src/ejemplo)
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,51,153), 2), "Registro de Personaje", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0,51,153)));
        jbtnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejemplo/add.png"))); // Icono botón (agrega add.png en src/ejemplo)
        jbtnCrear.setBackground(new java.awt.Color(0, 102, 204));
        jbtnCrear.setForeground(java.awt.Color.WHITE);
        jbtnCrear.setFont(new java.awt.Font("Arial", 1, 14));
        jftmNombre.setFont(new java.awt.Font("Arial", 0, 14));
        jpswContraseña.setFont(new java.awt.Font("Arial", 0, 14));
        jtxtaHistoria.setFont(new java.awt.Font("Arial", 0, 14));
        jspnNivel.setFont(new java.awt.Font("Arial", 0, 14));
        jsldExperiencia.setFont(new java.awt.Font("Arial", 0, 12));
        jpgsProgreso.setFont(new java.awt.Font("Arial", 1, 12));
        jlbNivelActual.setFont(new java.awt.Font("Arial", 1, 14));
        jlbNivelActual.setForeground(new java.awt.Color(0,102,51));
    }

    
    public void progreso(){
        int progreso = 0;
        try {
            String nombre = jftmNombre.getText().trim();
            String historia = jtxtaHistoria.getText().trim();
            int fuerza = calcularFuerzaContraseña(String.valueOf(jpswContraseña.getPassword()));
            Object nivelObj = jspnNivel.getValue();
            int nivel = (nivelObj instanceof Integer) ? (Integer)nivelObj : Integer.parseInt(nivelObj.toString());
            int experiencia = jsldExperiencia.getValue();
            if(nombre.length()>=3) progreso+=20;
            if(historia.length()>=10) progreso+=20;
            if(fuerza>=2) progreso+=20;
            if(nivel>0) progreso+=20;
            if(experiencia>1) progreso+=20;
            jpgsProgreso.setValue(progreso);
            mostrarValidaciones(nombre, historia, fuerza, nivel, experiencia);
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Error al calcular el progreso: " + ex.getMessage(),
                "Error de datos",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private int calcularFuerzaContraseña(String pass) {
    if (pass == null || pass.isEmpty()) {
        return 0; // Contraseña vacía o nula
    }

    int fuerza = 0;

    if (pass.length() >= 6) fuerza++;
    if (pass.matches(".*[A-Z].*")) fuerza++; // Contiene mayúsculas
    if (pass.matches(".*[0-9].*")) fuerza++; // Contiene números
    if (pass.matches(".*[!@#$%^&*()_+\\-=].*")) fuerza++; // Contiene caracteres especiales

    return fuerza;
}


    private void mostrarValidaciones(String nombre, String historia, int fuerza, int nivel, int experiencia) {
        StringBuilder msg = new StringBuilder();
        if(nombre.length()<3) msg.append("\n- El nombre debe tener al menos 3 caracteres.");
        if(historia.length()<10) msg.append("\n- La historia debe tener al menos 10 caracteres.");
        if(fuerza<2) msg.append("\n- La contraseña debe tener al menos 6 caracteres y una mayúscula o número.");
        if(nivel<1) msg.append("\n- El nivel debe ser mayor a 0.");
        if(experiencia<2) msg.append("\n- La experiencia debe ser mayor a 1.");
        jpgsProgreso.setToolTipText(msg.length()>0 ? "Faltan requisitos:"+msg.toString() : "¡Formulario completo!");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jftmNombre = new javax.swing.JFormattedTextField();
        jspnNivel = new javax.swing.JSpinner();
        jsldExperiencia = new javax.swing.JSlider();
        jlbNivelActual = new javax.swing.JLabel();
        jpswContraseña = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaHistoria = new javax.swing.JTextArea();
        jpgsProgreso = new javax.swing.JProgressBar();
        jbtnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        jLabel1.setText("Nombre");

        jLabel2.setText("Nivel");

        jLabel3.setText("Experiencia");

        jLabel4.setText("Contraseña");

        jLabel5.setText("Historia");

        jLabel6.setText("Progreso");

        try {
            jftmNombre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**********")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftmNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jftmNombreKeyReleased(evt);
            }
        });

        jspnNivel.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jspnNivel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspnNivelStateChanged(evt);
            }
        });

        jsldExperiencia.setMajorTickSpacing(10);
        jsldExperiencia.setPaintLabels(true);
        jsldExperiencia.setPaintTicks(true);
        jsldExperiencia.setValue(0);
        jsldExperiencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsldExperienciaStateChanged(evt);
            }
        });

        jpswContraseña.setColumns(5);
        jpswContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpswContraseñaKeyReleased(evt);
            }
        });

        jtxtaHistoria.setColumns(4);
        jtxtaHistoria.setLineWrap(true);
        jtxtaHistoria.setRows(2);
        jtxtaHistoria.setTabSize(4);
        jtxtaHistoria.setWrapStyleWord(true);
        jtxtaHistoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtaHistoriaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtxtaHistoria);

        jpgsProgreso.setForeground(new java.awt.Color(0, 51, 255));
        jpgsProgreso.setStringPainted(true);

        jbtnCrear.setText("Crear");
        jbtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jftmNombre)
                    .addComponent(jspnNivel)
                    .addComponent(jsldExperiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpswContraseña)
                    .addComponent(jScrollPane1)
                    .addComponent(jpgsProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbNivelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCrear)
                .addGap(156, 156, 156))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jftmNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jspnNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jsldExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNivelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jpswContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpgsProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jbtnCrear)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsldExperienciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsldExperienciaStateChanged
        jlbNivelActual.setText(""+jsldExperiencia.getValue());
        progreso();
    }//GEN-LAST:event_jsldExperienciaStateChanged

    private void jftmNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftmNombreKeyReleased
progreso();        // TODO add your handling code here:
    }//GEN-LAST:event_jftmNombreKeyReleased

    private void jspnNivelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspnNivelStateChanged
        progreso();        // TODO add your handling code here:
    }//GEN-LAST:event_jspnNivelStateChanged

    private void jpswContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpswContraseñaKeyReleased
progreso();        // TODO add your handling code here:
    }//GEN-LAST:event_jpswContraseñaKeyReleased

    private void jtxtaHistoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaHistoriaKeyReleased
progreso();        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtaHistoriaKeyReleased

    private void jbtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearActionPerformed
        // TODO add your handling code here:
        if(jpgsProgreso.getValue()<100){
            javax.swing.JOptionPane.showMessageDialog(this, jpgsProgreso.getToolTipText(), "Formulario incompleto", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            String nombre = jftmNombre.getText();
            String historia = jtxtaHistoria.getText();
            String contraseña = String.valueOf(jpswContraseña.getPassword());
            int experiencia = jsldExperiencia.getValue();
            Object nivelObj = jspnNivel.getValue();
            int nivel = (nivelObj instanceof Integer) ? (Integer)nivelObj : Integer.parseInt(nivelObj.toString());
            javax.swing.JPanel panel = new javax.swing.JPanel();
            panel.setLayout(new java.awt.GridLayout(0,1));
            panel.add(new javax.swing.JLabel("<html><b>Nombre:</b> "+nombre+"</html>"));
            panel.add(new javax.swing.JLabel("<html><b>Nivel:</b> "+nivel+"</html>"));
            panel.add(new javax.swing.JLabel("<html><b>Experiencia:</b> "+experiencia+"</html>"));
            panel.add(new javax.swing.JLabel("<html><b>Contraseña:</b> "+contraseña+"</html>"));
            panel.add(new javax.swing.JLabel("<html><b>Historia:</b> "+historia+"</html>"));
            javax.swing.JOptionPane.showMessageDialog(this, panel, "✅ Personaje Creado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            // Limpiar campos solo si el registro fue exitoso
            jftmNombre.setText("");
            jtxtaHistoria.setText("");
            jpswContraseña.setText("");
            jspnNivel.setValue(0);
            jsldExperiencia.setValue(0);
        } catch(NumberFormatException ex){
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error en el formato de número: " + ex.getMessage(),
                "Error de datos",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch(IllegalArgumentException ex){
            javax.swing.JOptionPane.showMessageDialog(this,
                "Datos inválidos: " + ex.getMessage(),
                "Error de validación",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch(Exception ex){
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error inesperado: " + ex.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCrear;
    private javax.swing.JFormattedTextField jftmNombre;
    private javax.swing.JLabel jlbNivelActual;
    private javax.swing.JProgressBar jpgsProgreso;
    private javax.swing.JPasswordField jpswContraseña;
    private javax.swing.JSlider jsldExperiencia;
    private javax.swing.JSpinner jspnNivel;
    private javax.swing.JTextArea jtxtaHistoria;
    // End of variables declaration//GEN-END:variables
}
