/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplo;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class RegistroPersonaje extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPersonaje
     */
    public RegistroPersonaje() {
        initComponents();
    }

    private void actualizarProgreso() {
        int progreso = 0;
        try {
            // Nombre
            if (!ftmNombre.getText().trim().isEmpty()) {
                progreso += 20;
            }
            // Clave
            if (pswClave.getPassword().length > 0) {
                progreso += 20;
            }
            // Historia
            if (!txaHistoria.getText().trim().isEmpty()) {
                progreso += 20;
            }
            // Nivel (Slider)
            if (jsldNivel.getValue() > 1) {
                progreso += 20;
            }
            // Vidas (Spinner)
            Object vidasObj = spnVidas.getValue();
            int vidas = 0;
            if (vidasObj instanceof Integer) {
                vidas = (Integer) vidasObj;
            } else {
                vidas = Integer.parseInt(vidasObj.toString());
            }
            if (vidas > 0) {
                progreso += 20;
            }
            prfProgreso.setValue(progreso);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Error al actualizar el progreso: " + ex.getMessage(),
                "Error de datos",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnVidas = new javax.swing.JSpinner();
        ftmNombre = new javax.swing.JFormattedTextField();
        pswClave = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaHistoria = new javax.swing.JTextArea();
        prfProgreso = new javax.swing.JProgressBar();
        jsldNivel = new javax.swing.JSlider();
        jlbNivel = new javax.swing.JLabel();
        jbtnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nivel");

        jLabel2.setText("Vidas");

        jLabel3.setText("Nombre");

        jLabel4.setText("Clave");

        jLabel5.setText("Historia");

        jLabel6.setText("Progreso");

        spnVidas.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spnVidas.setMaximumSize(new java.awt.Dimension(10, 10));
        spnVidas.setMinimumSize(new java.awt.Dimension(1, 1));
        spnVidas.setName("dddd"); // NOI18N
        spnVidas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnVidasStateChanged(evt);
            }
        });

        try {
            ftmNombre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*************** ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftmNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftmNombreActionPerformed(evt);
            }
        });
        ftmNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftmNombreKeyReleased(evt);
            }
        });

        pswClave.setColumns(10);
        pswClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswClaveKeyReleased(evt);
            }
        });

        txaHistoria.setColumns(4);
        txaHistoria.setLineWrap(true);
        txaHistoria.setRows(4);
        txaHistoria.setWrapStyleWord(true);
        txaHistoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txaHistoriaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txaHistoria);

        prfProgreso.setStringPainted(true);

        jsldNivel.setMajorTickSpacing(10);
        jsldNivel.setPaintLabels(true);
        jsldNivel.setPaintTicks(true);
        jsldNivel.setValue(0);
        jsldNivel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsldNivelStateChanged(evt);
            }
        });

        jbtnCrear.setText("Crear");
        jbtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnVidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftmNombre)
                            .addComponent(pswClave)
                            .addComponent(jScrollPane1)
                            .addComponent(prfProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(305, 305, 305))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jsldNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jlbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jbtnCrear)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jsldNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spnVidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ftmNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(pswClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prfProgreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnCrear)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftmNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftmNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftmNombreActionPerformed

    private void jsldNivelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsldNivelStateChanged
        jlbNivel.setText(""+jsldNivel.getValue());
        actualizarProgreso();

    }//GEN-LAST:event_jsldNivelStateChanged

    private void ftmNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftmNombreKeyReleased
        actualizarProgreso();
    }//GEN-LAST:event_ftmNombreKeyReleased

    private void pswClaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswClaveKeyReleased
actualizarProgreso();
        // TODO add your handling code here:
    }//GEN-LAST:event_pswClaveKeyReleased

    private void txaHistoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txaHistoriaKeyReleased
actualizarProgreso();
        // TODO add your handling code here:
    }//GEN-LAST:event_txaHistoriaKeyReleased

    private void spnVidasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnVidasStateChanged
actualizarProgreso();
        // TODO add your handling code here:
    }//GEN-LAST:event_spnVidasStateChanged

    private void jbtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearActionPerformed
        // TODO add your handling code here:
        if (prfProgreso.getValue() < 100) {
            JOptionPane.showMessageDialog(this,
                    "Faltan datos para completar el registro del personaje.",
                    "Formulario incompleto",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            // Si está completo, obtener datos
            String nombre = ftmNombre.getText();
            String clave = new String(pswClave.getPassword());
            String historia = txaHistoria.getText();
            int nivel = jsldNivel.getValue();
            Object vidasObj = spnVidas.getValue();
            int vidas = 0;
            if (vidasObj instanceof Integer) {
                vidas = (Integer) vidasObj;
            } else {
                vidas = Integer.parseInt(vidasObj.toString());
            }
            // Validaciones adicionales
            if (nombre.trim().isEmpty() || clave.trim().isEmpty() || historia.trim().isEmpty()) {
                throw new IllegalArgumentException("Algún campo está vacío.");
            }
            if (nivel < 1 || vidas < 1) {
                throw new IllegalArgumentException("Nivel o vidas no válidos.");
            }
            // Mostrar datos
            JOptionPane.showMessageDialog(this,
                    "✅ Personaje creado con éxito:\n\n" +
                    "Nombre: " + nombre + "\n" +
                    "Clave: " + clave + "\n" +
                    "Historia: " + historia + "\n" +
                    "Nivel: " + nivel + "\n" +
                    "Vidas: " + vidas,
                    "Personaje Creado",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error en el formato de número: " + ex.getMessage(),
                    "Error de datos",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this,
                    "Datos inválidos: " + ex.getMessage(),
                    "Error de validación",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        // Limpiar formulario
ftmNombre.setText("");
pswClave.setText("");
txaHistoria.setText("");
jsldNivel.setValue(0);
spnVidas.setValue(0);
prfProgreso.setValue(0);

    }//GEN-LAST:event_jbtnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftmNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCrear;
    private javax.swing.JLabel jlbNivel;
    private javax.swing.JSlider jsldNivel;
    private javax.swing.JProgressBar prfProgreso;
    private javax.swing.JPasswordField pswClave;
    private javax.swing.JSpinner spnVidas;
    private javax.swing.JTextArea txaHistoria;
    // End of variables declaration//GEN-END:variables
}
