/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplo;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DELL
 */
public class Tarjetas extends javax.swing.JFrame {

    /**
     * Creates new form Tarjetas
     */
    public Tarjetas() {
        initComponents();

        this.setTitle("CREADOR DE TARJETAS");
        this.setLocationRelativeTo(null);
        jpnlPrincipal.setVisible(false);
        jpnlBienvenido.setVisible(true);

    }

    private void empezar() {
        String nombre = JOptionPane.showInputDialog(this, "Nombre y apellido", "paso 1 de 2",
                JOptionPane.QUESTION_MESSAGE);
        if (nombre == null || nombre.trim().isEmpty()) {
            JOptionPane.showInputDialog(this, "FALTAN DATOS", "FALTA",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String cargo = JOptionPane.showInputDialog(this, "cargo", "paso 2 de 2",
                JOptionPane.QUESTION_MESSAGE);
        if (nombre == null || nombre.trim().isEmpty()) {
            JOptionPane.showInputDialog(this, "FALTAN DATOS", "FALTA",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        jblNombre.setText(nombre);
        jblnCargo.setText(cargo);
        jpnlBienvenido.setVisible(false);
        jpnlPrincipal.setVisible(true);

    }

    private void seleccionar() {
        try {
            JFileChooser selectedFile = new JFileChooser();
            selectedFile.setDialogTitle("Selecione una foto");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo tipo", "jpg", "png");
            selectedFile.setFileFilter(filter);
            int result = selectedFile.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File fileSelected = selectedFile.getSelectedFile();
                BufferedImage imageSelected = ImageIO.read(fileSelected);
                if (imageSelected == null) {
                    throw new IOException();
                }
                java.awt.Image imageR = imageSelected.getScaledInstance(jlblFoto.getWidth(), jlblFoto.getHeight(), java.awt.Image.SCALE_SMOOTH);

                ImageIcon imageFinal = new ImageIcon(imageR);
                jlblFoto.setIcon(imageFinal);
                jlblFoto.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "ERROR",
                        "OPERACION CANCELADA", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR AL CARGAR LA IMAGEN", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void seleccionarColor() {
        Color newColor = JColorChooser.showDialog(this, "SELECCIONE UN COLOR", jpnlPrincipal.getBackground());
        if (newColor != null) {
            jpnlPrincipal.setBackground(newColor);
        }
    }

    private void reset() {
        int confirm = JOptionPane.showConfirmDialog(this, "DESEA REINICIAR LA TARGETA",
                "CONFIRMAR", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        jpnlPrincipal.setVisible(false);
        jpnlBienvenido.setVisible(true);
        if (confirm == JOptionPane.YES_OPTION) {
            jblNombre.setText("");
            jblnCargo.setText("");
            jlblFoto.setIcon(null);
            jlblFoto.setText("FOTO DE PERFIL");
            jpnlPrincipal.setBackground(new Color(213, 217, 223));
        }else{
            JOptionPane.showMessageDialog(this, "ADIOS");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlBienvenido = new javax.swing.JPanel();
        jlblBienvenido = new javax.swing.JLabel();
        jbtnEmpezar = new javax.swing.JButton();
        jpnlPrincipal = new javax.swing.JPanel();
        jpnlTarjeta = new javax.swing.JPanel();
        jlblFoto = new javax.swing.JLabel();
        jblNombre = new javax.swing.JLabel();
        jblnCargo = new javax.swing.JLabel();
        jbtnColor = new javax.swing.JButton();
        jbtnFoto = new javax.swing.JButton();
        jbtnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlBienvenido.setMaximumSize(new java.awt.Dimension(300, 200));

        jlblBienvenido.setText("ESTE ES UN CREADOR DE TARJETAS");

        jbtnEmpezar.setText("BIENVENIDO");
        jbtnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmpezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlBienvenidoLayout = new javax.swing.GroupLayout(jpnlBienvenido);
        jpnlBienvenido.setLayout(jpnlBienvenidoLayout);
        jpnlBienvenidoLayout.setHorizontalGroup(
            jpnlBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlBienvenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnlBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlBienvenidoLayout.createSequentialGroup()
                        .addComponent(jbtnEmpezar)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlBienvenidoLayout.createSequentialGroup()
                        .addComponent(jlblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jpnlBienvenidoLayout.setVerticalGroup(
            jpnlBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlBienvenidoLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jlblBienvenido)
                .addGap(36, 36, 36)
                .addComponent(jbtnEmpezar)
                .addGap(21, 21, 21))
        );

        jpnlTarjeta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblFoto.setText("FOTO");
        jlblFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jblNombre.setText("NOMBRE");

        jblnCargo.setText("CARGO");

        javax.swing.GroupLayout jpnlTarjetaLayout = new javax.swing.GroupLayout(jpnlTarjeta);
        jpnlTarjeta.setLayout(jpnlTarjetaLayout);
        jpnlTarjetaLayout.setHorizontalGroup(
            jpnlTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(jpnlTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblnCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jpnlTarjetaLayout.setVerticalGroup(
            jpnlTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlTarjetaLayout.createSequentialGroup()
                        .addComponent(jblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jblnCargo)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jlblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jbtnColor.setText("Seleccionar Color");
        jbtnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnColorActionPerformed(evt);
            }
        });

        jbtnFoto.setText("Seleccionar Foto");
        jbtnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFotoActionPerformed(evt);
            }
        });

        jbtnReiniciar.setText("Reiniciar");
        jbtnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlPrincipalLayout = new javax.swing.GroupLayout(jpnlPrincipal);
        jpnlPrincipal.setLayout(jpnlPrincipalLayout);
        jpnlPrincipalLayout.setHorizontalGroup(
            jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jpnlTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jbtnFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnColor)
                        .addGap(63, 63, 63))))
            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jbtnReiniciar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnlPrincipalLayout.setVerticalGroup(
            jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jpnlTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnFoto)
                    .addComponent(jbtnColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jbtnReiniciar)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnlBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jpnlBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmpezarActionPerformed
        // TODO add your handling code here:
        empezar();
    }//GEN-LAST:event_jbtnEmpezarActionPerformed

    private void jbtnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFotoActionPerformed
        seleccionar();
    }//GEN-LAST:event_jbtnFotoActionPerformed

    private void jbtnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnColorActionPerformed
        seleccionarColor();
    }//GEN-LAST:event_jbtnColorActionPerformed

    private void jbtnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReiniciarActionPerformed
        reset();
    }//GEN-LAST:event_jbtnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarjetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jblNombre;
    private javax.swing.JLabel jblnCargo;
    private javax.swing.JButton jbtnColor;
    private javax.swing.JButton jbtnEmpezar;
    private javax.swing.JButton jbtnFoto;
    private javax.swing.JButton jbtnReiniciar;
    private javax.swing.JLabel jlblBienvenido;
    private javax.swing.JLabel jlblFoto;
    private javax.swing.JPanel jpnlBienvenido;
    private javax.swing.JPanel jpnlPrincipal;
    private javax.swing.JPanel jpnlTarjeta;
    // End of variables declaration//GEN-END:variables
}
